### PR TITLE
Remove incubating-related keyword

### PR DESCRIPTION
**Pull request by Yikf**

### CODE REVIEW

**Comment by Yikf** [comment]
cc @pan3793

**Review by pan3793 — APPROVED** [review]
LGTM, thanks

**Comment by yaooqinn** [comment]
image

this PR breaks the download links for some archived versions

**Comment by Yikf** [comment]
> image
> 
> this PR breaks the download links for some archived versions

I saw that you determine download url in https://github.com/apache/kyuubi-website/pull/104

**Pull request merged**
