### PR TITLE
Add Tianlin Liao in committer list

### PR DESCRIPTION
**Pull request by lightning-L**

### CODE REVIEW

**Comment by lightning-L** [comment]
@turboFei

**Comment by turboFei** [comment]
could you add a news as well?

**Comment by turboFei** [comment]
FYI:
```
To: dev@kyuubi.apache.org
Subject: [ANNOUNCEMENT] New Committer: Tianlin Liao


Hi Kyuubi Community,

The Project Management Committee (PMC) for Apache Kyuubi
has invited Tianlin Liao to become a committer and we are pleased 
to announce that she has accepted.

Tianlin Liao is working for eBay Shanghai.

She joined the Kyuubi community 1 year ago.

She contributed a lot for the Kyuubi client, including kyuubi-ctl, kyuubi-rest-client, kyuubi-jdbc, she also enhanced the Kyuubi metrics, and the Kyuubi Spark engine.

Now she is working on the jdbc session reconnect, which is significant for the Kyuubi community.

Being a committer enables easier contribution to the
project since there is no need to go via the patch
submission process. This should enable better productivity.
A PMC member helps manage and guide the direction of the project.

Please join me in congratulating Tianlin Liao!

Yours,
The Apache Kyuubi PMC
```

**Comment by lightning-L** [comment]
I refered previous news..

**Comment by turboFei** [comment]
It is fine, you can edit the news content by yourself.

**Review by turboFei — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merging to master

**Comment by turboFei** [comment]
have sent the announcement 

https://lists.apache.org/thread/wfvdbvr30zyngrp2pnvn3pcd395hx1m0

**Pull request merged**
